[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."canvas-to-notion"]
  timeout = 26

[dev]
  framework = "#static"
  publish = "."
  port = 8080
